spring.application.name=backend
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/KimKhiQuangHuong}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true